[package]
name = "objsh"
version = "0.1.0"
edition = "2021"
license = "MIT"
author = "梶塚太智<kajizukataichi@outlook.jp>"
description = "Object oriented shell"

[dependencies]
opener = "0.7.2"
rustyline = "14.0.0"
